apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category
  template:
    metadata:
      labels:
        app: category
    spec:
      containers:
        - name: category
          image: adwera/ts-tasks-category 
          env:
            - name: MONGO_URI
              value: 'mongodb://category-mongo-service:27017/category'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY 

---

apiVersion: v1
kind: Service
metadata:
  name: category-service
spec:
  selector:
    app: category
  type: LoadBalancer
  ports:
    - name: category
      protocol: TCP
      port: 5000
      targetPort: 5000


