apiVersion: apps/v1
kind: Deployment
metadata:
  name: section-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: section
  template:
    metadata:
      labels:
        app: section
    spec:
      containers:
        - name: section
          image: adwera/ts-tasks-section 
          env:
            - name: MONGO_URI
              value: 'mongodb://section-mongo-service:27017/section'
            - name: NATS_CLUSTER_ID
              value: 'tasks'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URI
              value: 'http://nats-service:4222'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY 

---

apiVersion: v1
kind: Service
metadata:
  name: section-service
spec:
  selector:
    app: section
  type: LoadBalancer
  ports:
    - name: section
      protocol: TCP
      port: 5000
      targetPort: 5000


